<?php
$routes = [
    'metadata',
    'getRequestToken', //1
    'getAccessToken', //1 
    'checkToken', //1
    'getUserComments', //1
    'getUserPhotos', //1
    'getBlogList', //1
    'getBlogServices', //1
    'addPhotoToBlog', //1
    'getCamerasBrandModels', //1
    'getCamerasBrands', //1
    'getCollectionInfo', //1
    'getCollectionsTree', //1
    'getCommonsInstitutions',
    'getContactsList',
    'getContactsListRecentlyUploaded',
    'getContactPublicList',
    'getContactsTaggingSuggestions',
    'addPhotoToFavoritesList',
    'getContextForFavorites',
    'getFavoritePhotosList',
    'getFavoritePublicPhotosList',
    'removePhotoFromFavoritesList',
    'addPhotoToGallery',
    'createGallery',
    'updateGalleryMetadata',
    'updateCommentForGalleryPhoto',
    'updatePhotosInGallery',
    'getGalleryInfo',
    'getGalleryListForPhoto',
    'getListOfPhotosForGallery',
    'removePhotoFromGallery',
    'browseGroup',
    'getGroupInfo',
    'joinGroup',
    'createRequestJoinGroup',
    'leaveGroup',
    'searchGroup',
    'addReplyToGroupDiscussionTopic',
    'deleteReplyFromGroupDiscussionTopic',
    'editTopicReplay',
    'getGroupTopicReplyInfo',
    'getListOfRepliesFromGroup',
    'addDiscussionTopicToGroup',
    'getGroupDiscussionTopicInfo',
    'getListDiscussionTopicsInGroup',
    'getMembersGroupList',
    'addPhotoToGroupPool',
    'getGroupsPoolsContext',
    'getGroupsPoolsList',
    'getGroupsPoolsPhoto',
    'deletePhotoFromGroupPool',
    'getInterestingPhotosByDate',
    'getMachineTagsNamespaces',
    'getMachineTagsPairs',
    'getMachineTagsPredicates',
    'getMachineTagsRecentValues',
    'getMachineTagsValues',
    'getPandaList',
    'getPandaPhotos',
    'getPeopleByEmail',
    'getPeopleByUsername',
    'getUserGroups',
    'getUserInfo',
    'getPhotoVideoLimits',
    'getUserPhoto',
    'getParticularMemberPhotos',
    'getUserPublicGroups',
    'getUserPublicPhotos',
    'getUploadStatus',
    'addTagsToPhoto',
    'deletePhoto',
    'getAllPhotoContexts',
    'getUserContactsPhotos',
    'getUserContactsPublicPhotos',
    'getPhotoStreamContexts',
    'getPhotosCountsForDateRanges',
    'getExifTagsForPhoto',
    'getPeopleByFavoritePhotoId',
    'getPhotoInfo',
    'getNotInSetPhoto',
    'getPermissionsForPhoto',
    'getPopularPhotos',
    'getRecentPhotos',
    'getPhotoSizes',
    'getUntaggedPhotos',
    'getGeoTaggedPhotos',
    'getPhotosWithoutGeoData',
    'getRecentlyUpdatedPhotos',
    'removeTagFromPhoto',
    'searchPhotos',
    'setContentTypeOfPhoto',
    'setPhotoDates',
    'setMetaInformationForPhoto',
    'setPermissionsForPhoto',
    'setSafetyLevelOfPhoto',
    'setTagsForPhoto',
    'addCommentToPhoto',
    'deleteCommentFromPhoto',
    'getPhotoComments',
    'updatePhotoComment',
    'getPhotoCommentsForContacts',
    'batchCorrectPhotoLocation',
    'correctPhotoGeoLocation',
    'getGeoDataForPhoto',
    'getPermissionsForPhotoGeoData',
    'getPhotosByCoordinates',
    'removePhotoGeoData',
    'setGeoTagForPhoto',
    'setGeoLocationForPhoto',
    'setPermissionForGeoDataPhoto',
    'uploadPhoto'
];
foreach($routes as $file) {
    require __DIR__ . '/../src/routes/'.$file.'.php';
}

